#!/bin/sh

# http://themarinaatroweswharf.com/assets/img/markers/
# http://www.gulfshoresal.gov/gis/markers/

# Blue
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerA.png" -O blueA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerB.png" -O blueB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerC.png" -O blueC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerD.png" -O blueD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerE.png" -O blueE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerF.png" -O blueF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerG.png" -O blueG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerH.png" -O blueH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerI.png" -O blueI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerJ.png" -O blueJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerK.png" -O blueK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerL.png" -O blueL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerM.png" -O blueM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerN.png" -O blueN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerO.png" -O blueO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerP.png" -O blueP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerQ.png" -O blueQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerR.png" -O blueR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerS.png" -O blueS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerT.png" -O blueT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerU.png" -O blueU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerV.png" -O blueV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerW.png" -O blueW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerX.png" -O blueX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerY.png" -O blueY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/blue_MarkerZ.png" -O blueZ.png

# Red
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerA.png" -O redA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerB.png" -O redB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerC.png" -O redC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerD.png" -O redD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerE.png" -O redE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerF.png" -O redF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerG.png" -O redG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerH.png" -O redH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerI.png" -O redI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerJ.png" -O redJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerK.png" -O redK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerL.png" -O redL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerM.png" -O redM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerN.png" -O redN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerO.png" -O redO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerP.png" -O redP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerQ.png" -O redQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerR.png" -O redR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerS.png" -O redS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerT.png" -O redT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerU.png" -O redU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerV.png" -O redV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerW.png" -O redW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerX.png" -O redX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerY.png" -O redY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/red_MarkerZ.png" -O redZ.png

# Green
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerA.png" -O greenA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerB.png" -O greenB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerC.png" -O greenC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerD.png" -O greenD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerE.png" -O greenE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerF.png" -O greenF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerG.png" -O greenG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerH.png" -O greenH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerI.png" -O greenI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerJ.png" -O greenJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerK.png" -O greenK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerL.png" -O greenL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerM.png" -O greenM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerN.png" -O greenN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerO.png" -O greenO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerP.png" -O greenP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerQ.png" -O greenQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerR.png" -O greenR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerS.png" -O greenS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerT.png" -O greenT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerU.png" -O greenU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerV.png" -O greenV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerW.png" -O greenW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerX.png" -O greenX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerY.png" -O greenY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/green_MarkerZ.png" -O greenZ.png

# Yellow
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerA.png" -O yellowA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerB.png" -O yellowB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerC.png" -O yellowC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerD.png" -O yellowD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerE.png" -O yellowE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerF.png" -O yellowF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerG.png" -O yellowG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerH.png" -O yellowH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerI.png" -O yellowI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerJ.png" -O yellowJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerK.png" -O yellowK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerL.png" -O yellowL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerM.png" -O yellowM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerN.png" -O yellowN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerO.png" -O yellowO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerP.png" -O yellowP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerQ.png" -O yellowQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerR.png" -O yellowR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerS.png" -O yellowS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerT.png" -O yellowT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerU.png" -O yellowU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerV.png" -O yellowV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerW.png" -O yellowW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerX.png" -O yellowX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerY.png" -O yellowY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/yellow_MarkerZ.png" -O yellowZ.png

# Purple
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerA.png" -O purpleA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerB.png" -O purpleB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerC.png" -O purpleC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerD.png" -O purpleD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerE.png" -O purpleE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerF.png" -O purpleF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerG.png" -O purpleG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerH.png" -O purpleH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerI.png" -O purpleI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerJ.png" -O purpleJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerK.png" -O purpleK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerL.png" -O purpleL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerM.png" -O purpleM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerN.png" -O purpleN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerO.png" -O purpleO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerP.png" -O purpleP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerQ.png" -O purpleQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerR.png" -O purpleR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerS.png" -O purpleS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerT.png" -O purpleT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerU.png" -O purpleU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerV.png" -O purpleV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerW.png" -O purpleW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerX.png" -O purpleX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerY.png" -O purpleY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/purple_MarkerZ.png" -O purpleZ.png

# Brown
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerA.png" -O brownA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerB.png" -O brownB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerC.png" -O brownC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerD.png" -O brownD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerE.png" -O brownE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerF.png" -O brownF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerG.png" -O brownG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerH.png" -O brownH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerI.png" -O brownI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerJ.png" -O brownJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerK.png" -O brownK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerL.png" -O brownL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerM.png" -O brownM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerN.png" -O brownN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerO.png" -O brownO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerP.png" -O brownP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerQ.png" -O brownQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerR.png" -O brownR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerS.png" -O brownS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerT.png" -O brownT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerU.png" -O brownU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerV.png" -O brownV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerW.png" -O brownW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerX.png" -O brownX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerY.png" -O brownY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/brown_MarkerZ.png" -O brownZ.png

# Dark green
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerA.png" -O darkgreenA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerB.png" -O darkgreenB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerC.png" -O darkgreenC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerD.png" -O darkgreenD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerE.png" -O darkgreenE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerF.png" -O darkgreenF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerG.png" -O darkgreenG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerH.png" -O darkgreenH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerI.png" -O darkgreenI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerJ.png" -O darkgreenJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerK.png" -O darkgreenK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerL.png" -O darkgreenL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerM.png" -O darkgreenM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerN.png" -O darkgreenN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerO.png" -O darkgreenO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerP.png" -O darkgreenP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerQ.png" -O darkgreenQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerR.png" -O darkgreenR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerS.png" -O darkgreenS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerT.png" -O darkgreenT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerU.png" -O darkgreenU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerV.png" -O darkgreenV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerW.png" -O darkgreenW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerX.png" -O darkgreenX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerY.png" -O darkgreenY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/darkgreen_MarkerZ.png" -O darkgreenZ.png

# Orange
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerA.png" -O orangeA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerB.png" -O orangeB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerC.png" -O orangeC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerD.png" -O orangeD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerE.png" -O orangeE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerF.png" -O orangeF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerG.png" -O orangeG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerH.png" -O orangeH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerI.png" -O orangeI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerJ.png" -O orangeJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerK.png" -O orangeK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerL.png" -O orangeL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerM.png" -O orangeM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerN.png" -O orangeN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerO.png" -O orangeO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerP.png" -O orangeP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerQ.png" -O orangeQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerR.png" -O orangeR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerS.png" -O orangeS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerT.png" -O orangeT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerU.png" -O orangeU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerV.png" -O orangeV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerW.png" -O orangeW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerX.png" -O orangeX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerY.png" -O orangeY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/orange_MarkerZ.png" -O orangeZ.png

# Pale blue
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerA.png" -O paleblueA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerB.png" -O paleblueB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerC.png" -O paleblueC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerD.png" -O paleblueD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerE.png" -O paleblueE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerF.png" -O paleblueF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerG.png" -O paleblueG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerH.png" -O paleblueH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerI.png" -O paleblueI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerJ.png" -O paleblueJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerK.png" -O paleblueK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerL.png" -O paleblueL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerM.png" -O paleblueM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerN.png" -O paleblueN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerO.png" -O paleblueO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerP.png" -O paleblueP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerQ.png" -O paleblueQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerR.png" -O paleblueR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerS.png" -O paleblueS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerT.png" -O paleblueT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerU.png" -O paleblueU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerV.png" -O paleblueV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerW.png" -O paleblueW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerX.png" -O paleblueX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerY.png" -O paleblueY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/paleblue_MarkerZ.png" -O paleblueZ.png

# Pink
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerA.png" -O pinkA.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerB.png" -O pinkB.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerC.png" -O pinkC.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerD.png" -O pinkD.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerE.png" -O pinkE.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerF.png" -O pinkF.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerG.png" -O pinkG.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerH.png" -O pinkH.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerI.png" -O pinkI.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerJ.png" -O pinkJ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerK.png" -O pinkK.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerL.png" -O pinkL.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerM.png" -O pinkM.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerN.png" -O pinkN.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerO.png" -O pinkO.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerP.png" -O pinkP.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerQ.png" -O pinkQ.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerR.png" -O pinkR.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerS.png" -O pinkS.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerT.png" -O pinkT.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerU.png" -O pinkU.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerV.png" -O pinkV.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerW.png" -O pinkW.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerX.png" -O pinkX.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerY.png" -O pinkY.png
wget "http://themarinaatroweswharf.com/assets/img/markers/pink_MarkerZ.png" -O pinkZ.png
